# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "connectedAndroidTest")
  end

  desc "Take screenshots with the current version of the app"
  lane :screenshots do
    gradle(task: "assemble", build_type: "Debug")
    gradle(task: "assemble", build_type: "AndroidTest")
    capture_android_screenshots(
        app_package_name: 'fr.quentinklein.stickynotifs.debug',
        app_apk_path: 'app/build/outputs/apk/debug/app-debug.apk',
        tests_apk_path: 'app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
        locales: ["fr-FR"],
        clear_previous_screenshots: true
    )
  end

  desc "Submit a new Beta Build to Play Store Beta"
  lane :beta do
    gradle(task: "assemble", build_type: "Release")
    upload_to_play_store(track: 'beta')
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assemble", build_type: "Release")
    upload_to_play_store
  end
end
